# Generated by Django 4.2.10 on 2025-04-26 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trajets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('nb_places', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('CONFIRME', 'Confirmée'), ('ANNULEE', 'Annulée'), ('ATTENTE', 'En attente'), ('TERMINEE', 'Terminée')], default='ATTENTE', max_length=20)),
                ('code_reservation', models.CharField(max_length=20, unique=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('informations_passagers', models.TextField(blank=True, help_text='Informations sur les passagers supplémentaires')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajets.trajet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
