# Generated by Django 4.2.10 on 2025-04-26 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compagnies', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_permis', models.CharField(max_length=100, unique=True)),
                ('date_emission_permis', models.DateField()),
                ('date_expiration_permis', models.DateField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_SERVICE', 'En service'), ('EN_PAUSE', 'En pause'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=50)),
                ('localisation_actuelle', models.CharField(blank=True, max_length=255)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Expérience en années')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducteurs', to='compagnies.compagnietransport')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
