# Generated by Django 4.2.10 on 2025-04-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('OM', 'Orange Money'), ('WAVE', 'Wave'), ('CB', 'Carte Bancaire'), ('PAYPAL', 'PayPal'), ('ESPECES', 'Espèces')], max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('REUSSI', 'Réussi'), ('ECHEC', 'Échoué'), ('EN_ATTENTE', 'En attente'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='reservations.reservation')),
            ],
        ),
    ]
