# Generated by Django 4.2.10 on 2025-04-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compagnies', '0001_initial'),
        ('conducteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('capacite', models.PositiveIntegerField()),
                ('modele', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('annee_fabrication', models.PositiveIntegerField()),
                ('type_vehicule', models.CharField(choices=[('BUS', 'Bus'), ('MINIBUS', 'Minibus'), ('VAN', 'Van'), ('VOITURE', 'Voiture')], max_length=20)),
                ('localisation_actuelle', models.CharField(blank=True, max_length=255)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_dernier_entretien', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='compagnies.compagnietransport')),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='conducteurs.conducteur')),
            ],
        ),
    ]
