# Generated by Django 4.2.10 on 2025-04-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
        ('conducteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('lieu_depart', models.CharField(max_length=255)),
                ('lieu_arrivee', models.CharField(max_length=255)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee_estimee', models.DateTimeField()),
                ('date_arrivee_reelle', models.DateTimeField(blank=True, null=True)),
                ('nombre_places_total', models.PositiveIntegerField()),
                ('nombre_places_reservees', models.PositiveIntegerField(default=0)),
                ('prix_par_place', models.DecimalField(decimal_places=2, max_digits=10)),
                ('covoiturage', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PROGRAMME', max_length=20)),
                ('latitude_actuelle', models.FloatField(blank=True, null=True)),
                ('longitude_actuelle', models.FloatField(blank=True, null=True)),
                ('derniere_maj_position', models.DateTimeField(blank=True, null=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='conducteurs.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='vehicules.vehicule')),
            ],
        ),
    ]
